# Generated by Django 5.0.3 on 2024-03-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='mini_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
